### ISSUE TITLE
종목 선택 기능

### ISSUE THREAD

**Issue by falsetru** [seirion/WorldDodook#3]
- 종목이름으로 검색, 선택할 수 있는 팝업을 제공해주세요.
  - 입력예: `한국전력`
  - 선택: `015760 코스피 한국전력`, `052690 코스피 한국전력기술`
- 마지막으로 선택했던 종목을 기억하고, 다음번 기동시 선택된 종목을 조회해야함

**Comment by seirion** [comment]
이슈는 어떻게 닫습니까 ?
